services:
  db:
    container_name: open_fls_db
    image: mysql:8.4.0
    restart: always
    env_file: docker-compose.env
    volumes:
      - open-fls-db:/var/lib/mysql
    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password
      - db_user
    networks:
      - open-fls-network
    command: --innodb-fast-shutdown=0

  adminer:
    container_name: open_fls_adminer
    image: adminer:4.8.1
    restart: always
    networks:
      - open-fls-network

  frontend:
    container_name: open_fls_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: DEV
    restart: always
    volumes:
      - ../frontend:/app
    networks:
      - open-fls-network

  proxy:
    container_name: open_fls_proxy
    image: nginx
    env_file: docker-compose.env
    restart: always
    volumes:
      - ../proxy/nginx-dev.conf:/etc/nginx/nginx.conf
      - ${LOG_PATH}:/var/log/nginx/
    depends_on:
      - db
      - frontend
      - adminer
    ports:
      - ${PORT}:8000
    networks:
      - open-fls-network

networks:
  open-fls-network:
    internal: false

secrets:
  db_password:
    file: ../secrets/db_password.secret
  db_root_password:
    file: ../secrets/db_root_password.secret
  db_user:
    file: ../secrets/db_user.secret

volumes:
  open-fls-db:
