services:
  db:
    container_name: open_fls_db
    image: mysql:8.4.0
    restart: always
    env_file: docker-compose.env
    volumes:
      - open-fls-db:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
      - db_user
    networks:
      - open-fls-network
    command: --innodb-fast-shutdown=0

  adminer:
    container_name: open_fls_adminer
    image: adminer:4.8.1
    restart: always
    networks:
      - open-fls-network

  backend:
    container_name: open_fls_backend
    image: ghcr.io/pendragonax/openfls-backend:2.0.1
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./logs:/app/logs/
    depends_on:
      - db
    secrets:
      - db_root_password
      - db_password
      - db_user
    networks:
      - open-fls-network

  frontend:
    container_name: open_fls_frontend
    image: ghcr.io/pendragonax/openfls-frontend:2.0.1
    volumes:
      - ../proxy/nginx.frontend.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - open-fls-network

  proxy:
    container_name: open_fls_proxy
    image: nginx:1.28.1
    restart: always
    volumes:
     - ../proxy/ssl.nginx.conf:/etc/nginx/nginx.conf
     - ./logs:/var/log/nginx/
     - ./ssl-bundle.crt:/etc/nginx/ssl-bundle.crt
     - ./ssl-key.key:/etc/nginx/ssl-key.key
    depends_on:
      - db
      - backend
      - frontend
      - adminer
    ports:
      - "8000:8000"
    networks:
      - open-fls-network

networks:
  open-fls-network:
    internal: false

secrets:
  db_password:
    file: ../secrets/db_password.secret
  db_root_password:
    file: ../secrets/db_root_password.secret
  db_user:
    file: ../secrets/db_user.secret

volumes:
  open-fls-db:
